USE [master]
GO

/****** Object:  Database [FirstDatabase]    Script Date: 8/16/2022 8:18:58 PM ******/
CREATE DATABASE [FirstDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FirstDatabase', FILENAME = N'C:\SQL_Data_File\FirstDatabase.mdf' , SIZE = 65536KB , MAXSIZE = 1048576KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FirstDatabase_log', FILENAME = N'C:\SQL_Log_Files\FirstDatabase_log.ldf' , SIZE = 32768KB , MAXSIZE = 524288KB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FirstDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FirstDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FirstDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FirstDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FirstDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FirstDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [FirstDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FirstDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FirstDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FirstDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FirstDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FirstDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FirstDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FirstDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FirstDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FirstDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FirstDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FirstDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FirstDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FirstDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FirstDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FirstDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FirstDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FirstDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FirstDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [FirstDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FirstDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FirstDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FirstDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FirstDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FirstDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FirstDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FirstDatabase] SET  READ_WRITE 
GO


